# Font
window:
  decorations: none
  opacity: 0.97
  startup_mode: Maximized

font:
  size: 12

  normal:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Regular

  bold:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Bold

  italic:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Italic

# Colors (One Dark - custom)
colors:
  transparent_background_colors: true
  # Default colors
  primary:
    background: '#1f2329'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#131613'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

